# Introduction to Mathematical Matrices

A **matrix** is a rectangular array of numbers arranged in rows and columns.
It’s a foundational concept in linear algebra, used in everything from solving systems of equations to powering machine learning models.

## What is a Matrix?

Example of a 2×3 matrix:

\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix}

In [1]:
# Python list of lists
matrix_py = [[1, 2, 3],
             [4, 5, 6]]

# NumPy array
import numpy as np
matrix_np = np.array([[1, 2, 3],
                      [4, 5, 6]])

matrix_py, matrix_np

([[1, 2, 3], [4, 5, 6]],
 array([[1, 2, 3],
        [4, 5, 6]]))

## Matrix Dimensions (Shape)

In [2]:
# Python
rows_py = len(matrix_py)
cols_py = len(matrix_py[0])

# NumPy
shape_np = matrix_np.shape

(rows_py, cols_py), shape_np

((2, 3), (2, 3))

## Transpose of a Matrix

Flips rows into columns and columns into rows.

In [3]:
# Python
transpose_py = list(zip(*matrix_py))

# NumPy
transpose_np = matrix_np.T

transpose_py, transpose_np

([(1, 4), (2, 5), (3, 6)],
 array([[1, 4],
        [2, 5],
        [3, 6]]))

## Matrix Addition

Two matrices of the same shape can be added element-wise.

In [4]:
A = [[1, 2], [3, 4]]
B = [[5, 6], [7, 8]]

# Python
add_py = [[A[i][j] + B[i][j] for j in range(len(A[0]))] for i in range(len(A))]

# NumPy
A_np = np.array(A)
B_np = np.array(B)
add_np = A_np + B_np

add_py, add_np

([[6, 8], [10, 12]],
 array([[ 6,  8],
        [10, 12]]))

## Matrix Multiplication

Matrix multiplication is **not** element-wise — it involves dot products of rows and columns.

In [5]:
# Python (manual dot product)
result_py = [[sum(a*b for a, b in zip(A_row, B_col)) 
              for B_col in zip(*B)] for A_row in A]

# NumPy
result_np = A_np @ B_np  # or np.dot(A_np, B_np)

result_py, result_np

([[19, 22], [43, 50]],
 array([[19, 22],
        [43, 50]]))

## Identity Matrix

An identity matrix has 1s on the diagonal and 0s elsewhere.

In [6]:
# Python
identity_py = [[1 if i == j else 0 for j in range(3)] for i in range(3)]

# NumPy
identity_np = np.eye(3)

identity_py, identity_np

([[1, 0, 0], [0, 1, 0], [0, 0, 1]],
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

## Comparison of List of Lists vs. NumPy 2D Array

### Matrix Operations

| Concept            | Python (List of Lists)              | NumPy Array                      |
|--------------------|-------------------------------------|----------------------------------|
| Create Matrix      | `[[1,2],[3,4]]`                     | `np.array([[1,2],[3,4]])`        |
| Shape              | `len(mat), len(mat[0])`             | `mat.shape`                      |
| Transpose          | `list(zip(*mat))`                   | `mat.T`                          |
| Addition           | Nested loops                        | `A + B`                          |
| Multiplication     | Manual dot product                  | `A @ B` or `np.dot(A, B)`        |
| Identity Matrix    | List comprehension                  | `np.eye(n)`                      |

###  Characteristics

| Feature               | List of Lists                                           | NumPy `ndarray`                                 |
| --------------------- | ------------------------------------------------------- | ----------------------------------------------- |
| **Shape enforcement** | None — inner lists can be different lengths             | Fixed rectangular shape                         |
| **Data types**        | Can mix types freely                                    | All elements share the same dtype               |
| **Memory layout**     | Pointers to separate list objects (scattered in memory) | Contiguous block of memory (fast for math)      |
| **Performance**       | Slower for large numeric ops (Python loops)             | Vectorized C‑level operations, much faster      |
| **Flexibility**       | Can be jagged, hold any objects                         | Must be rectangular and typed                   |
| **Built‑in math**     | None — you write loops manually                         | Rich API: broadcasting, slicing, linear algebra |